# .readthedocs.yml

version: 2

# Build all formats
formats: all

build:
  os: "ubuntu-22.04"
  tools:
    python: 3.11

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .